BEGIN;

ALTER TABLE "AiChatMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiRecommendation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BookEmbedding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GenrePointPrediction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SearchEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SearchEventTag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TagSubterm" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserRecommendation" ENABLE ROW LEVEL SECURITY;

COMMIT;
